# Generated by Django 5.1.6 on 2025-02-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_recompute_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpart',
            name='subpart_id',
            field=models.CharField(max_length=50),
        ),
    ]
